name: example
description: Example using drift with drift_sqflite

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ^2.10.3

dependencies:
  drift:
  drift_sqflite:
  provider: ^6.0.2
  rxdart: ^0.27.3
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.0
  drift_dev:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  drift:
    path: ../../drift
  drift_dev:
    path: ../../drift_dev
  drift_sqflite:
    path: ../
