name: drift_core
description: Core components for a SQL query builder in Dart applications.
version: 0.1.0-dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  convert: ^3.0.1
  meta: ^1.7.0

dev_dependencies:
  lints: ^1.0.0
